### ISSUE TITLE
A possible off-by-one error when flipping y coord

### ISSUE THREAD

**Issue by ptpt** [mapzen/mapbox-vector-tile#53]
Both the README and the spec v1 state that coordinates must be within 0 to 4095 i.e. `[0, EXTENT)`

When you flip the y coord, [the code](https://github.com/mapzen/mapbox-vector-tile/blob/master/mapbox_vector_tile/encoder.py#L408):

```python
if not y_coord_down:
    y = self.extents - y
```

will convert `y=0` to `y=4096` which will cause a point feature at `y=0` (expected to show at the bottom of the tile) won't show up at all.

**Comment by ptpt** [comment]
Also in README,

> For example, POINT(0 0) is the lower left corner of the tile and POINT(4096, 4096) is the upper right corner of the tile.

The upper right corner of the tile should be `POINT(4095 4095)`. `POINT(4096 4096)` should be complete out of the tile.

**Comment by zerebubuth** [comment]
The most recent version of the [Mapbox vector tile specification](https://github.com/mapbox/vector-tile-spec/tree/master/2.1) says:

> For example, if a tile has an extent of 4096, coordinate units within the tile refer to 1/4096th of its square dimensions. A coordinate of 0 is on the top or left edge of the tile, and a coordinate of 4096 is on the bottom or right edge.

The coordinate `(4096, 4096)` would therefore be the lower right corner and `(0, 0)` the upper left of the encoded vector tile. This is different from how one usually thinks about images with discrete (raster) pixels, where the pixel at index `[4095, 4095]` is the corner pixel, but has an unspoken implicit width and height of 1 pixel - meaning it extends up to the corner `(4096, 4096)`.

In this library the default is to flip `y` and therefore the documentation says that `y` grows up and therefore `POINT(0, 0)` is the _lower_ left, and `POINT(4096, 4096)` the _upper_ right. This is correct for using this library in its default configuration and conventional in "geographic coordinates" which usually have `y` up. However, the Mapbox vector tile format has `y` down, which is conventional in "graphics coordinates".

**Comment by ptpt** [comment]
Hi @zerebubuth Thanks for the clarifying how the coordinates work.

However, the issue is still here. Encoding a `POINT (X 0)` feature (which will flip to `POINT (X 4096)`) nothing will show on the map. If I encode `POINT(X 1)`, a point will show at the bottom of the tile. Is this by design? i.e. the minimal y must be 1?

And also this library doesn't encode to the latest version 2.1. It still uses version 1 by default.

**Comment by zerebubuth** [comment]
Hmmm... sorry, I think I didn't explain that very well. Perhaps a diagram would help:

![circle4219](https://cloud.githubusercontent.com/assets/271360/15607243/44ed93a2-2409-11e6-91dd-22c24bdaa4f4.png)

The diagram represents a vector tile in `y`-up "geographic" coordinates, with three points:

* blue at `(1024, 0)`
* green at `(4096, 2048)`
* red at `(3072, 4224)`

These will be transformed into Mapbox vector tile coordinates:

* blue at `(1024, 4096)`
* green at `(4096, 2048)`
* red at `(3072, -128)`

All of these would be encoded in the tile. It is standard practice in some Mapbox vector tile sources to include features in a "buffer" which extends beyond the 0-4096 limits of the visible tile, as features have physical extents beyond their zero-width representations. In the diagram above, all the points extend within the visible area of the tile, even the red point which has a centre outside of the visible area of the tile.

For Mapzen's vector tiles, we do not buffer the visible extent of the tile, so would not include the red point. However, that clipping operation occurs in the [tilequeue](https://github.com/mapzen/tilequeue/) library which uses this one, and the way in which the clipping is done would include both the blue and green points as they are on the boundary. This library encodes all features regardless of whether they are in the visible 0-4096 extent of the tile, so can be used with or without the "buffer" - it's up to the code which calls it.

To be clear: A point encoded at `(X, 0)` will be flipped to `(X, 4096)` and output in the tile. `(X, 4096)` is a valid coordinate to appear in an MVT-encoded tile. We have tests which encode `POINT(0 0)` and decode it again ([example](https://github.com/mapzen/mapbox-vector-tile/blob/master/tests/test_encoder.py#L196)) without issue.

It is possible that some rendering software might not support coordinates outside the range 0-4095. What rendering software are you using?

Regarding MVT spec versions; although we don't yet output conforming v2.1 tiles, the v2.1 spec is much more detailed than previous documents. The method by which tile extents and coordinates are encoded hasn't changed since v1.0, so I linked to v2.1 for the clearer documentation.

**Comment by ptpt** [comment]
Thanks again. Yes it is rendering on mapbox-gl-js. Do you think it could be the problem?

I set up a simple page: http://mm.mapillary.io/index2.html

The code to generate the tiles:

```python
import shapely.geometry
def genfeature(x, y):
    return {'geometry': shapely.geometry.Point(x, y)}

# set 1
features = [genfeature(x * 100, 1) for x in range(20)]

# set 2: at y = 0 don't show at all
features += [genfeature(2000 + x * 100, 0) for x in range(20)]

# set 3
features += [genfeature(n * 100, n * 100) for n in range (int(4096/100))]

layer = {'name': 'mapillary-images', 'features': features}
content = mvt.encode(layer)

# then write the same content to all tiles
```

Would be nice you can test it using other rendering software. The temporary testing endpoint is at http://mm.mapillary.io/tiles5001/{z}/{x}/{y}.mapbox

**Comment by zerebubuth** [comment]
I see what you mean with the Mapbox GL JS example. It's clearly not showing all the points. I'm afraid I don't know enough about Mapbox GL to know whether that's the expected behaviour or not.

[Here's a similar example](http://mapzen.com/tangram/play/?scene=https%3A%2F%2Fapi.github.com%2Fgists%2F4e155a56148a745859cc1dfb6a5d470d#12/55.6165/12.9735) using Tangram JS, and (on my computer) all the points are visible:

![tangram-fri may 27 2016 16-50-05 gmt 0100 bst](https://cloud.githubusercontent.com/assets/271360/15613382/2629c0f4-242b-11e6-9e91-763e3406f5e4.png)

Just to check further, I downloaded that tile `12/2195/1283` and decoded it using `protoc --decode mapnik.vector.tile -I./mapbox_vector_tile/Mapbox ./mapbox_vector_tile/Mapbox/vector_tile.proto < 1283.mapbox`, which gives something like the following (edited for brevity):

```
layers {
  name: "mapillary-images"
  features {
    type: Point
    geometry: 9
    geometry: 0
    geometry: 8190
  }
  features {
    type: Point
    geometry: 9
    geometry: 200
    geometry: 8190
  }
[...]
  features {
    type: Point
    geometry: 9
    geometry: 5000
    geometry: 8192
  }
  features {
    type: Point
    geometry: 9
    geometry: 5200
    geometry: 8192
  }
[...]
  extent: 4096
  version: 1
}
```

In the MVT format, single points with positive coordinates are encoded as:

```
geometry: 9
geometry: 2 * x
geometry: 2 * y
```

The first `geometry: 9` just means "one `move_to` follows". When the third `geometry` changes from `8190` (which is `y=1` flipped and zig-zag encoded) to `8192` (`y=0`), it shows that all the data is present in the tile, but not being rendered for some reason.

Hope that helps.

**Comment by ptpt** [comment]
It's likely to a rendering problem with the Mapbox client. I will check with them.

Thank you very much for the help. Keep up the good work!

**Comment by loicgasser** [comment]
I am just putting it out there but did you include a buffer around your tile ? Points may disappear or appear cutted if you don't. Usually the default value is around 100px. 

So you may actually have values below 0 and above 4095 encoded in the tile. 

another thing you could check is the pixel ratio which is:
nb of possible vals in your tile / screen resolution of your tile 

4096 / 256 = 16 (Usually the default value)
